### ISSUE TITLE
Low download speed using HTTP download from Nemo

### ISSUE THREAD

**Issue by Xuyuch** [nemoarchive/documentation#3]
Hi Nemo team
I faced an significant data download speed drop since Feb 15, 2024. before that my download speed is around 30 MB/s, and now is around 70kb/s and the connection is not stable. I tried on several workstations, our schools HPC, also my home internet and all of them have a really low download speed. Also, the website of the Nemo database started to stuck from then on. Could you please help me check if there is something happened to the Nemo's download server? If it real happens, is there a mirror server that is not affected?  
Thanks ahead.

**Comment by tkhodges** [comment]
We have resolved the issue with the HTTPS release area.  Please let us know if you are still having problems with downloading.
